"""Generate the four bilingual static travel pages. Run with python3 scripts/build_travel.py."""
from pathlib import Path
from html import escape
ROOT = Path(__file__).resolve().parents[1]
def t(ja,ko,tag='span',cls=''):
    return f'<{tag}'+(f' class="{cls}"' if cls else '')+f' data-ja="{escape(ja,quote=True)}" data-ko="{escape(ko,quote=True)}">{escape(ja)}</{tag}>'
def link(url,ja,ko,cls='button'):
    return f'<a class="{cls}" href="{url}">{t(ja,ko)}</a>'
P=[dict(id='airport',name=('仁川・金浦空港送迎','인천·김포공항 송영'),unit=('専用車1台・片道','전용차량 1대·편도'),desc=('空港からホテルへ。荷物の多い日も、移動をシンプルに。','공항에서 호텔까지. 짐이 많은 날에도 편안하게 이동하세요.'),aud=('初めての韓国旅行・家族旅行に','첫 한국 여행·가족 여행에'),image='hyundai-staria-exterior.jpg',scope=('仁川・金浦空港 ⇔ ソウル市内の宿泊先','인천·김포공항 ⇔ 서울 시내 숙소'),included=('車両・ドライバー、出発前の日本語での合流案内','차량·기사, 출발 전 일본어 미팅 안내'),extra=('往復、経由地、深夜・早朝、チャイルドシートは事前相談','왕복, 경유지, 심야·이른 아침, 카시트는 사전 상담'),conditions=('空港・送迎先・人数・荷物・時間帯でお見積もり。通行料、駐車料、無料待機時間と延長料金を見積書でご案内します。','공항·목적지·인원·짐·시간대에 따라 견적을 안내합니다. 통행료, 주차료, 무료 대기 시간과 초과 요금은 견적서에서 확인하세요.'),examples=[('到着日のホテル送迎','도착일 호텔 송영','空港で合流 → ご宿泊先へ。合流場所は事前にご案内します。','공항 미팅 → 숙소 이동. 미팅 장소는 사전에 안내합니다.'),('帰国日の空港送迎','귀국일 공항 송영','ホテルで合流 → 空港へ。フライトに合わせて出発時間をご相談。','호텔 미팅 → 공항 이동. 항공편에 맞춰 출발 시간을 조율합니다.')]),
dict(id='seoul-tour',name=('ソウル貸切観光6時間','서울 전용차량 관광 6시간'),unit=('専用車1台・6時間','전용차량 1대·6시간'),desc=('家族や友人のペースで。行きたい場所を、ひとつのルートに。','가족과 친구의 속도에 맞춰. 가고 싶은 곳을 하나의 동선으로.'),aud=('家族・友人旅行におすすめ','가족·친구 여행에 추천'),image='seoul-night-hero.jpg',scope=('ソウル市内発着・6時間のモデルプラン','서울 시내 출발·도착, 6시간 기본 구성'),included=('車両・ドライバー、事前の観光ルート相談','차량·기사, 사전 관광 동선 상담'),extra=('日本語同行ガイド、時間延長、ソウル郊外への訪問は別途相談','일본어 동행 가이드, 시간 연장, 서울 외곽 방문은 별도 상담'),conditions=('車種・日程・ルートによりお見積もり。食事、入場料、買い物代は別途。駐車料・延長料金の扱いは予約前にご確認ください。','차종·일정·동선에 따라 견적을 안내합니다. 식사·입장료·쇼핑 비용은 별도입니다. 주차료·초과 요금 조건은 예약 전에 확인하세요.'),examples=[('はじめてのソウル','첫 서울 여행','景福宮 → 仁寺洞 → 明洞。定番の街を組み合わせるコース例。','경복궁 → 인사동 → 명동. 대표 명소를 조합한 코스 예시.'),('親と一緒に、ゆったり','부모님과 여유롭게','観光 → 食事 → カフェ。歩く距離や休憩を相談して調整。','관광 → 식사 → 카페. 걷는 거리와 휴식을 고려해 조율.'),('友人とショッピング','친구와 쇼핑','聖水や江南など、ご希望エリアを中心にルートを相談。','성수·강남 등 희망 지역을 중심으로 동선을 상담.')]),
dict(id='business',name=('韓国出張サポート8時間','한국 출장 지원 8시간'),unit=('車両＋通訳者・8時間','차량＋통역사·8시간'),desc=('企業訪問も、商談も。移動と通訳をまとめて調整。','기업 방문부터 미팅까지. 이동과 통역을 함께 조율합니다.'),aud=('企業訪問・展示会・商談に','기업 방문·전시회·미팅에'),image='genesis-g90-exterior.jpg',scope=('訪問地域・業務内容を確認して個別手配','방문 지역·업무 내용을 확인 후 개별 수배'),included=('車両・ドライバー、別途手配する業務通訳者、移動日程の調整','차량·기사, 별도로 배정하는 업무 통역사, 이동 일정 조율'),extra=('専門分野の通訳、地方出張、空港送迎、時間延長は別途相談','전문 분야 통역, 지방 출장, 공항 송영, 시간 연장은 별도 상담'),conditions=('通訳分野・訪問先・時間により個別見積もり。担当者の対応可否、資料共有・秘密保持、必要書類について予約前に確認します。','통역 분야·방문처·시간에 따라 개별 견적을 안내합니다. 담당자 배정 가능 여부, 자료 공유·비밀유지, 필요 서류를 예약 전에 확인합니다.'),examples=[('企業訪問の一日','기업 방문 일정','ホテル → 訪問先 → 商談 → ホテル。移動時間を含めて調整。','호텔 → 방문처 → 미팅 → 호텔. 이동 시간을 포함해 조율.'),('展示会・商談への同行','전시회·미팅 동행','会場への移動と通訳を相談。専門分野は事前確認が必要です。','행사장 이동과 통역을 상담하세요. 전문 분야는 사전 확인이 필요합니다.')])]
def cards(base):
    out='<div class="product-grid">'
    for i,p in enumerate(P):
        out+=f'<article class="product-card {"featured" if i==1 else ""}"><div class="card-image"><img src="{base}../images/korea-travel/{p["image"]}" alt="" loading="lazy">'+t(*p['aud'],cls='tag')+'</div><div class="card-body"><span class="number">0'+str(i+1)+'</span>'+t(*p['name'],'h3')+t(*p['desc'],'p','card-desc')+t(*p['unit'],'p','unit')+t('日程・条件に合わせてお見積もり','일정·조건에 맞춰 견적 안내','p','muted')+link(base+p['id']+'/', '内容・料金条件を見る →','구성·요금 조건 보기 →')+'</div></article>'
    return out+'</div>'
def form(selected='airport'):
    options=''.join(f'<option value="{p["id"]}" {"selected" if p["id"]==selected else ""} data-ja="{p["name"][0]}" data-ko="{p["name"][1]}">{p["name"][0]}</option>' for p in P)
    def field(id,ja,ko,typ='text',required=False):
        return '<label>'+t(ja,ko)+f'<input id="{id}" name="{id}" type="{typ}" '+('required ' if required else '')+('min="1" max="30" ' if typ=='number' else '')+'></label>'
    return '<section id="contact" class="section contact"><div class="wrap contact-layout"><div>'+t('YOUR NEXT TRIP','YOUR NEXT TRIP','p','eyebrow')+t('ご予定をお聞かせください。','여행 일정을 알려주세요.','h2')+t('必要なサービスを選んで、見積もり内容をメールで相談できます。','필요한 서비스를 선택하고 견적 내용을 이메일로 상담하세요.','p')+'<a class="email-link" href="mailto:info@stemcarejapan.com">info@stemcarejapan.com ↗</a>'+t('フォームでは予約は確定しません。条件・金額・手配可否をご確認のうえ、お申し込みください。','이 양식으로 예약이 확정되지는 않습니다. 조건·금액·수배 가능 여부를 확인한 후 신청해 주세요.','p','muted')+'</div><form id="quote-form"><div class="form-grid"><label class="full">'+t('サービス','서비스')+'<select id="service" name="service">'+options+'</select></label>'+field('date','利用日（必須）','이용일 (필수)','date',True)+field('people','人数（必須）','인원 (필수)','number',True)+'<div class="full dynamic-fields" id="service-fields"></div>'+field('name','お名前（必須）','성함 (필수)','text',True)+field('email','メールアドレス（必須）','이메일 (필수)','email',True)+'<label class="full">'+t('その他のご希望','추가 요청 사항')+'<textarea name="message" rows="3" maxlength="2000"></textarea></label></div>'+t('次のボタンでメールアプリが開きます。内容を確認して送信してください。このページからは送信・保存されません。','아래 버튼으로 메일 앱이 열립니다. 내용을 확인하고 직접 전송해 주세요. 이 페이지에서는 전송·저장되지 않습니다.','p','form-note')+'<div class="form-actions"><button class="button" type="submit">'+t('見積もりメールを作成','견적 문의 메일 작성')+'</button><button class="text-button" type="button" id="copy-quote">'+t('内容をコピー','내용 복사')+'</button></div><p id="form-status" role="status" aria-live="polite"></p><textarea id="quote-output" hidden readonly aria-label="Email draft"></textarea></form></div></section>'
def common(base,content,title,selected='airport'):
    asset=base+'../'
    nav=''.join(link(base+'#'+id,ja,ko,'nav-link') for id,ja,ko in [('products','サービス','대표상품'),('compare','料金について','요금 안내'),('process','ご利用方法','이용 방법'),('faq','よくある質問','자주 묻는 질문')])
    return '<!doctype html><html lang="ja" data-default-lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' | StemCareJapan</title><meta name="description" content="仁川・金浦空港送迎、ソウル貸切観光6時間、韓国出張サポート8時間。サービス内容と料金条件を確認し、日本語で見積もり相談。"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&amp;family=Noto+Sans+JP:wght@400;500;600;700&amp;family=Noto+Sans+KR:wght@400;500;600;700&amp;family=Noto+Serif+JP:wght@400;500;600&amp;family=Noto+Serif+KR:wght@400;500;600&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="'+asset+'css/travel.css"></head><body><a class="skip" href="#main">'+t('本文へ','본문으로')+'</a><header class="header"><div class="wrap header-inner"><a class="brand" href="'+(base or './')+'"><strong>StemCare<span>Japan</span></strong>'+t('韓国旅行・滞在サポート','한국 여행·체류 지원','small')+'</a><nav id="navigation" aria-label="Main">'+nav+'</nav><div class="header-actions"><button class="lang active" data-language="ja" aria-pressed="true">JA</button><button class="lang" data-language="ko" aria-pressed="false">KO</button>'+link('#contact','見積相談','견적 상담','button small')+'<button id="menu-toggle" aria-controls="navigation" aria-expanded="false" aria-label="Menu">☰</button></div></div></header><main id="main">'+content+form(selected)+'</main><footer class="wrap footer"><div><a class="brand" href="'+(base or './')+'">StemCareJapan</a>'+t('韓国の移動と滞在を、日本語で。','한국의 이동과 체류를 일본어로.','p')+'</div><div>'+link(asset,'サービス一覧','전체 서비스','footer-link')+link(base+'#additional','その他のご相談','기타 상담','footer-link')+'<p>© 2026 StemCareJapan</p></div><p class="credits">'+t('写真：車両はメーカー提供の参考画像です。車種・仕様・配車可否は見積時に確認します。','사진: 차량은 제조사 제공 참고 이미지입니다. 차종·사양·배차 가능 여부는 견적 시 확인합니다.')+' <a href="https://newsroom.genesis.com/genesis-g90/">Genesis</a> · <a href="https://www.hyundai.com/worldwide/en/mpv/staria-2021/highlights">Hyundai</a> · <a href="https://commons.wikimedia.org/wiki/File:Seoul_cityscape_by_night.jpg">Seoul / Wikimedia Commons</a></p></footer><div class="mobile-bar">'+link(base+'#products','サービスを見る','상품 보기','mobile-secondary')+link('#contact','日本語で見積相談','일본어 견적 상담')+'</div><script src="'+asset+'js/travel.js" defer></script></body></html>'
hero='<section class="hero"><div class="wrap hero-layout"><div class="hero-copy">'+t('JAPAN → KOREA','JAPAN → KOREA','p','eyebrow')+t('移動も、通訳も。\n日本語で相談。','이동도, 통역도.\n일본어로 상담하세요.','h1')+t('空港送迎・ソウル貸切観光・出張サポート','공항 송영·서울 차량 관광·출장 지원','p','hero-lead')+t('ご家族との旅から、大切な商談まで。\n韓国でのご予定に合うサービスをお選びください。','가족과의 여행부터 중요한 미팅까지.\n한국 방문 일정에 맞는 서비스를 선택하세요.','p')+'<div class="hero-actions">'+link('#products','3つのサービスを見る ↘','대표상품 3가지 보기 ↘')+link('#contact','日本語で相談する','일본어로 상담하기','text-link')+'</div></div><div class="hero-photo"><img src="../images/korea-travel/seoul-night-hero.jpg" alt="ソウルの夜景" fetchpriority="high"><div class="photo-caption"><span>SEOUL, YOUR WAY.</span>'+t('あなたのペースで楽しむ韓国。','당신의 속도로 즐기는 한국.')+'</div></div></div></section>'
products='<section id="products" class="section"><div class="wrap"><div class="section-heading"><div>'+t('01 / OUR SERVICES','01 / OUR SERVICES','p','eyebrow')+t('ご予定に合う、3つのサービス。','일정에 맞춰 고르는 세 가지 서비스.','h2')+'</div>'+t('送迎だけのご相談も承ります。','송영만 필요한 경우에도 상담할 수 있습니다.','p','muted')+'</div>'+cards('')+'</div></section>'
compare='<section id="compare" class="section tint"><div class="wrap">'+t('02 / CLEAR DETAILS','02 / CLEAR DETAILS','p','eyebrow')+t('予約前に、内容と費用を確認。','예약 전에 구성과 비용을 확인하세요.','h2')+t('料金は日程・車種・ご依頼内容によって異なります。総額と追加料金の条件を確認してからご予約ください。','요금은 일정·차종·요청 내용에 따라 달라집니다. 총액과 추가 요금 조건을 확인한 뒤 예약해 주세요.','p')+'<div class="table-scroll"><table><caption class="sr-only">'+t('サービス比較','상품 비교')+'</caption><thead><tr><th scope="col">'+t('サービス','상품')+'</th><th scope="col">'+t('基本構成','기본 구성')+'</th><th scope="col">'+t('別途確認すること','별도 확인 사항')+'</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+t(*p['name'])+'</th><td>'+t(*p['included'])+'</td><td>'+t(*p['extra'])+'</td></tr>' for p in P)+'</tbody></table></div></div></section>'
trust='<section class="section"><div class="wrap"><div class="section-heading"><div>'+t('03 / BEFORE YOU BOOK','03 / BEFORE YOU BOOK','p','eyebrow')+t('旅の前に、気になることを。','출발 전에 궁금한 것부터.','h2')+'</div></div><div class="info-grid">'+''.join('<article><span class="number">'+n+'</span>'+t(j,k,'h3')+t(d,e,'p')+'</article>' for n,j,k,d,e in [('01','日本語で事前相談','일본어 사전 상담','送迎場所や訪問先を出発前に確認。ドライバーの日本語対応と同行通訳の有無は個別にご案内します。','출발 전에 미팅 장소와 방문처를 확인합니다. 기사의 일본어 대응과 동행 통역 여부는 개별 안내합니다.'),('02','人数と荷物に合う車両','인원과 짐에 맞는 차량','セダン・バンなど、ご利用人数と荷物に合わせて相談。車種と配車可否は見積時に確認します。','세단·밴 등 인원과 짐에 맞춰 상담합니다. 차종과 배차 가능 여부는 견적 시 확인합니다.'),('03','追加費用と変更条件','추가 비용과 변경 조건','待機・延長・キャンセル条件を予約前に確認。対応可能な時間や連絡方法もご案内します。','대기·연장·취소 조건을 예약 전에 확인합니다. 대응 가능 시간과 연락 방법도 안내합니다.')])+'</div></div></section>'
process='<section id="process" class="section tint"><div class="wrap">'+t('04 / HOW IT WORKS','04 / HOW IT WORKS','p','eyebrow')+t('相談からご利用まで。','상담부터 이용까지.','h2')+'<ol class="steps">'+''.join('<li>'+t(j,k,'h3')+t(d,e,'p')+'</li>' for j,k,d,e in [('サービスを選ぶ','상품 선택','ご希望の日程・人数をお知らせください。','희망 일정과 인원을 알려주세요.'),('見積もりを確認','견적 확인','内容・総額・手配可否・取消条件を確認。','구성·총액·수배 가능 여부·취소 조건을 확인합니다.'),('予約を確定','예약 확정','案内された支払い方法・確定条件に沿ってお手続き。','안내된 결제 방법과 확정 조건에 따라 진행합니다.'),('韓国でご利用','한국에서 이용','事前に確認した場所・時間に合流。','사전에 확인한 장소와 시간에 만납니다.')])+'</ol></div></section>'
faqs=[('料金は1人あたりですか？','요금은 1인 기준인가요?','送迎・貸切観光は車両1台が基本単位です。出張は車両と通訳者を含めて個別見積もりします。','송영·차량 관광은 차량 1대가 기본 단위입니다. 출장은 차량과 통역사를 포함해 개별 견적을 안내합니다.'),('ドライバーは日本語を話しますか？','기사가 일본어를 구사하나요?','日本語での予約相談と、ドライバーの日本語対応は異なります。同行ガイド・通訳が必要な場合はお知らせください。','일본어 예약 상담과 기사의 일본어 대응은 다릅니다. 동행 가이드·통역이 필요하면 알려주세요.'),('フライトの遅延や予定変更は？','항공편 지연이나 일정 변경은 어떻게 하나요?','待機時間・追加料金・連絡先は予約前に確認します。変更が分かった時点で担当窓口へご連絡ください。','대기 시간·추가 요금·연락처는 예약 전에 확인합니다. 변경 사실을 알게 되면 담당 창구로 연락해 주세요.'),('キャンセル料はかかりますか？','취소 수수료가 있나요?','サービス・日程・手配状況により異なります。見積もり時に取消期限と料金を確認してからお申し込みください。','서비스·일정·수배 상황에 따라 달라집니다. 견적 시 취소 기한과 비용을 확인한 후 신청해 주세요.'),('見積もり相談で予約は確定しますか？','견적 상담으로 예약이 확정되나요?','確定しません。対応可否と条件をご確認いただき、担当者から予約確定の案内を受けてください。','확정되지 않습니다. 제공 가능 여부와 조건을 확인하고 담당자의 예약 확정 안내를 받아주세요.')]
faq='<section id="faq" class="section"><div class="wrap narrow">'+t('よくある質問','자주 묻는 질문','h2')+''.join('<details><summary>'+t(j,k)+'</summary>'+t(d,e,'p')+'</details>' for j,k,d,e in faqs)+'<details id="additional"><summary>'+t('ホテル・美容相談・複合日程について','호텔·미용 상담·복합 일정 안내')+'</summary>'+t('ホテルや複合日程も個別にご相談ください。美容分野は相談予約・通訳・移動の支援であり、医療行為は提供しません。対応範囲は事前に確認します。','호텔과 복합 일정도 개별 상담할 수 있습니다. 미용 분야는 상담 예약·통역·이동 지원이며 의료행위를 제공하지 않습니다. 대응 범위는 사전에 확인합니다.','p')+'</details></div></section>'
(ROOT/'korea-travel/index.html').write_text(common('',hero+products+compare+trust+process+faq,'韓国の空港送迎・貸切観光・出張サポート').replace('><', '>\n<')+'\n',encoding='utf8')
for i,p in enumerate(P):
    content='<section class="detail-hero"><div class="wrap">'+link('../#products','← サービス一覧','← 전체 상품','text-link')+'<div class="detail-layout"><div>'+t(*p['aud'],'p','eyebrow')+t(*p['name'],'h1')+t(*p['desc'],'p','hero-lead')+t(*p['unit'],'p','unit')+link('#contact','このサービスの見積もりを相談','이 상품 견적 상담')+'</div><img src="../../images/korea-travel/'+p['image']+'" alt="" class="detail-photo"></div></div></section><section class="section tint"><div class="wrap detail-layout"><div>'+t('サービス内容・料金条件','상품 구성·요금 조건','h2')+t(*p['conditions'],'p')+'</div><dl class="specs">'+''.join('<div>'+t(j,k,'dt')+t(*p[key],'dd')+'</div>' for j,k,key in [('利用範囲','이용 범위','scope'),('基本構成','기본 구성','included'),('追加のご相談','추가 상담','extra')])+'</dl></div></section><section class="section"><div class="wrap">'+t('ご利用イメージ','이용 예시','h2')+'<div class="info-grid">'+''.join('<article>'+t(j,k,'h3')+t(d,e,'p')+'</article>' for j,k,d,e in p['examples'])+'</div>'+t('上記はモデル例です。交通状況・営業時間・手配可否に合わせて調整します。','위 내용은 예시입니다. 교통·영업시간·수배 가능 여부에 맞춰 조율합니다.','p','muted')+'</div></section>'+process+faq
    dest=ROOT/'korea-travel'/p['id'];dest.mkdir(exist_ok=True)
    (dest/'index.html').write_text(common('../',content,p['name'][0],p['id']).replace('><', '>\n<')+'\n',encoding='utf8')
